# Generated by Django 4.2 on 2023-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='feedimg')),
                ('disc', models.TextField()),
            ],
        ),
    ]
