# Generated by Django 4.2 on 2023-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statiapp', '0004_place_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='meet_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='mimage')),
                ('disc', models.TextField()),
            ],
        ),
    ]
