# Generated by Django 4.2 on 2023-04-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statiapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
